# Generated by Django 3.2.15 on 2022-08-09 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktailapp', '0003_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comments',
        ),
    ]
