# Generated by Django 3.2.15 on 2022-08-09 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktailapp', '0004_rename_comment_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
