# Generated by Django 3.2.15 on 2022-08-18 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktailapp', '0006_alter_post_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, to='cocktailapp.category'),
        ),
    ]
