# Generated by Django 3.2.15 on 2022-09-05 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktailapp', '0008_auto_20220905_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='stars',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
