# Generated by Django 3.2.15 on 2022-09-07 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktailapp', '0009_alter_post_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='stars',
        ),
    ]
