# Generated by Django 3.2.15 on 2022-09-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktailapp', '0011_auto_20220908_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
