# Generated by Django 3.2.15 on 2022-09-09 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktailapp', '0016_alter_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
