# Generated by Django 3.2.15 on 2022-09-13 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktailapp', '0020_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
