# Generated by Django 3.2.15 on 2022-09-14 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktailapp', '0029_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
