# Generated by Django 3.2.15 on 2022-09-15 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktailapp', '0031_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
